import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marcelo
 */
public class AppAlterar extends javax.swing.JInternalFrame {

    /**
     * Creates new form AppAlterar
     */
    public AppAlterar(LinkedList<Aviador>a){
        piloto = a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        anomeLbl = new javax.swing.JLabel();
        anomeTx = new javax.swing.JTextField();
        aenderecoLbl = new javax.swing.JLabel();
        aenderecoTx = new javax.swing.JTextField();
        afoneLbl = new javax.swing.JLabel();
        afoneTx = new javax.swing.JFormattedTextField();
        aemailLbl = new javax.swing.JLabel();
        aemailTx = new javax.swing.JTextField();
        anumeroBrvLbl = new javax.swing.JLabel();
        anumeroBrvTx = new javax.swing.JTextField();
        ctitulacao = new javax.swing.JLabel();
        aanoConLbl = new javax.swing.JLabel();
        aanoConTx = new javax.swing.JFormattedTextField();
        anInstLbl = new javax.swing.JLabel();
        anInstTx = new javax.swing.JTextField();
        acidadeLbl = new javax.swing.JLabel();
        acidadeTx = new javax.swing.JTextField();
        adadosPessoais = new javax.swing.JLabel();
        aregistroLbl = new javax.swing.JLabel();
        aregistroTx = new javax.swing.JTextField();
        aufLbl = new javax.swing.JLabel();
        aufTx = new javax.swing.JTextField();
        experienciaProfissional = new javax.swing.JLabel();
        adataInicLbl = new javax.swing.JLabel();
        adataInicTx = new javax.swing.JFormattedTextField();
        adataTermLbl = new javax.swing.JLabel();
        adataTermTx = new javax.swing.JFormattedTextField();
        adescricaoLbl = new javax.swing.JLabel();
        adescricaoTx = new javax.swing.JTextField();
        aempresaLbl = new javax.swing.JLabel();
        aempresaTx = new javax.swing.JTextField();
        acidadeProfLbl = new javax.swing.JLabel();
        acidadeProfTx = new javax.swing.JTextField();
        aestadoLbl = new javax.swing.JLabel();
        aestadoTx = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        ctipoDeAeronave = new javax.swing.JLabel();
        amodeloLbl = new javax.swing.JLabel();
        amodeloTx = new javax.swing.JTextField();
        acapacidadeLbl = new javax.swing.JLabel();
        acapacidadeTx = new javax.swing.JFormattedTextField();
        ahLbl = new javax.swing.JLabel();
        ahTx = new javax.swing.JFormattedTextField();
        aAtualizarButton = new javax.swing.JButton();
        aConsultarButton = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        aLimparButton = new javax.swing.JButton();
        AnteriorButton2 = new javax.swing.JButton();
        AlterarButton2 = new javax.swing.JButton();
        ProximoButton2 = new javax.swing.JButton();
        AnteriorButton3 = new javax.swing.JButton();
        AlterarButton3 = new javax.swing.JButton();
        ProximoButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Atualizar Piloto");

        anomeLbl.setText("Nome : ");

        anomeTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anomeTxActionPerformed(evt);
            }
        });
        anomeTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anomeTxKeyTyped(evt);
            }
        });

        aenderecoLbl.setText(" Endereço : ");

        aenderecoTx.setEditable(true);
        aenderecoTx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                aenderecoTxFocusLost(evt);
            }
        });
        aenderecoTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aenderecoTxActionPerformed(evt);
            }
        });
        aenderecoTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aenderecoTxKeyTyped(evt);
            }
        });

        afoneLbl.setText(" Fone : ");

        afoneTx.setEditable(true);
        try {
            afoneTx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        afoneTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afoneTxActionPerformed(evt);
            }
        });
        afoneTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                afoneTxKeyTyped(evt);
            }
        });

        aemailLbl.setText(" Email : ");

        aemailTx.setEditable(true);
        aemailTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aemailTxActionPerformed(evt);
            }
        });
        aemailTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aemailTxKeyTyped(evt);
            }
        });

        anumeroBrvLbl.setText(" Número do Brevê : ");

        anumeroBrvTx.setEditable(true);
        anumeroBrvTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anumeroBrvTxKeyTyped(evt);
            }
        });

        ctitulacao.setText(" TITULAÇÃO");

        aanoConLbl.setText("(Ano de Conclusão) : ");

        aanoConTx.setEditable(true);
        aanoConTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aanoConTxActionPerformed(evt);
            }
        });
        aanoConTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aanoConTxKeyTyped(evt);
            }
        });

        anInstLbl.setText("Nome da Instituição : ");

        anInstTx.setEditable(true);
        anInstTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anInstTxKeyTyped(evt);
            }
        });

        acidadeLbl.setText("Cidade : ");

        acidadeTx.setEditable(true);
        acidadeTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acidadeTxActionPerformed(evt);
            }
        });

        adadosPessoais.setText(" DADOS PESSOAIS");

        aregistroLbl.setText("Registro Profissional : ");

        aregistroTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aregistroTxKeyTyped(evt);
            }
        });

        aufLbl.setText("UF : ");

        aufTx.setEditable(true);
        aufTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aufTxActionPerformed(evt);
            }
        });
        aufTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aufTxKeyTyped(evt);
            }
        });

        experienciaProfissional.setText(" EXPERIÊNCIA PROFISSIONAL");

        adataInicLbl.setText(" Data de inicio : ");

        adataInicTx.setEditable(true);
        try {
            adataInicTx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        adataInicTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adataInicTxActionPerformed(evt);
            }
        });

        adataTermLbl.setText("Data de Termino : ");

        adataTermTx.setEditable(true);
        try {
            adataTermTx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        adescricaoLbl.setText(" Descrição da Atividade : ");

        adescricaoTx.setEditable(true);

        aempresaLbl.setText("Empresa : ");

        aempresaTx.setEditable(true);

        acidadeProfLbl.setText("Cidade : ");

        acidadeProfTx.setEditable(true);

        aestadoLbl.setText("Estado : ");

        aestadoTx.setEditable(true);

        ctipoDeAeronave.setText("TIPO DE AERONAVE APTA A PILOTAR ");

        amodeloLbl.setText(" Modelo : ");

        amodeloTx.setEditable(true);

        acapacidadeLbl.setText("Capacidade de Passageiros : ");

        acapacidadeTx.setEditable(true);

        ahLbl.setText("Horas de Vôo : ");

        ahTx.setEditable(true);

        aAtualizarButton.setText("Atualizar");
        aAtualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAtualizarButtonActionPerformed(evt);
            }
        });

        aConsultarButton.setText("Consultar");
        aConsultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aConsultarButtonActionPerformed(evt);
            }
        });

        aLimparButton.setText("Limpar");
        aLimparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLimparButtonActionPerformed(evt);
            }
        });

        AnteriorButton2.setText("Anterior");
        AnteriorButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorButton2ActionPerformed(evt);
            }
        });

        AlterarButton2.setText("Alterar");
        AlterarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarButton2ActionPerformed(evt);
            }
        });

        ProximoButton2.setText("Próximo");
        ProximoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoButton2ActionPerformed(evt);
            }
        });

        AnteriorButton3.setText("Anterior");
        AnteriorButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorButton3ActionPerformed(evt);
            }
        });

        AlterarButton3.setText("Alterar");
        AlterarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarButton3ActionPerformed(evt);
            }
        });

        ProximoButton3.setText("Próximo");
        ProximoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator9)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adadosPessoais)
                            .addComponent(ctipoDeAeronave)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(amodeloLbl)
                                        .addGap(8, 8, 8)
                                        .addComponent(amodeloTx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(acapacidadeLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(acapacidadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(aLimparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aConsultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(aAtualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ahLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ahTx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AnteriorButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(AlterarButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(ProximoButton3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aanoConLbl)
                                        .addGap(8, 8, 8)
                                        .addComponent(aanoConTx, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(anInstLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(anInstTx, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(acidadeLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(acidadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(aufLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(aufTx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(anomeLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(anomeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aenderecoLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(aenderecoTx, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(afoneLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(afoneTx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(anumeroBrvLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(anumeroBrvTx, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(aemailLbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(aemailTx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(107, 107, 107)
                                        .addComponent(aregistroLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(aregistroTx, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ctitulacao)
                                    .addComponent(experienciaProfissional)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(adataInicLbl)
                                        .addGap(8, 8, 8)
                                        .addComponent(adataInicTx, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(adataTermLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(adataTermTx, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(adescricaoLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(adescricaoTx, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(aempresaLbl)))
                                .addGap(18, 18, 18)
                                .addComponent(aempresaTx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(acidadeProfLbl)
                                .addGap(18, 18, 18)
                                .addComponent(acidadeProfTx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(aestadoLbl)
                                .addGap(18, 18, 18)
                                .addComponent(aestadoTx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(886, 886, 886)
                                .addComponent(AnteriorButton2)
                                .addGap(18, 18, 18)
                                .addComponent(AlterarButton2)
                                .addGap(18, 18, 18)
                                .addComponent(ProximoButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addComponent(jSeparator7)
            .addComponent(jSeparator8)
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(adadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anomeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aenderecoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aenderecoTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afoneTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aemailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aemailTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anumeroBrvLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anumeroBrvTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aregistroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aregistroTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aanoConLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aanoConTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anInstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anInstTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acidadeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acidadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aufLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aufTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(experienciaProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adataInicTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adataTermLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adataInicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adataTermTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adescricaoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adescricaoTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aempresaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aempresaTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acidadeProfLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acidadeProfTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aestadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aestadoTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnteriorButton2)
                    .addComponent(AlterarButton2)
                    .addComponent(ProximoButton2))
                .addGap(16, 16, 16)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctipoDeAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlterarButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(amodeloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amodeloTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acapacidadeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acapacidadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ahLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ahTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ProximoButton3)
                        .addComponent(AnteriorButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aAtualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aConsultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLimparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anomeTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anomeTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anomeTxActionPerformed

    private void aenderecoTxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aenderecoTxFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_aenderecoTxFocusLost

    private void aenderecoTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aenderecoTxActionPerformed

    }//GEN-LAST:event_aenderecoTxActionPerformed

    private void afoneTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afoneTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afoneTxActionPerformed

    private void aanoConTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aanoConTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aanoConTxActionPerformed

    private void adataInicTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adataInicTxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_adataInicTxActionPerformed

    private void aAtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAtualizarButtonActionPerformed
        // TODO add your handling code here:
         Aviador piloto = null;
        if(anomeTx.getText().toString().equals("") || aenderecoTx.getText().toString().equals("") || afoneTx.getText().toString().equals("(  )         ")  || aemailTx.getText().toString().equals("") || anumeroBrvTx.getText().toString().equals("") || aregistroTx.getText().toString().equals("") || aanoConTx.getText().toString().equals("") || anInstTx.getText().toString().equals("") || acidadeTx.getText().toString().equals("") || aufTx.getText().toString().equals("") || adataInicTx.getText().toString().equals("  /  /    ")  || adataTermTx.getText().toString().equals("  /  /    ")  || adescricaoTx.getText().toString().equals("") || aempresaTx.getText().toString().equals("")|| acidadeProfTx.getText().toString().equals("") || aestadoTx.getText().toString().equals("")|| amodeloTx.getText().toString().equals("") ||acapacidadeTx.getText().toString().equals("") || ahTx.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para prosseguir!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }else{
                try{
                    piloto = new Aviador(anomeTx.getText(),aenderecoTx.getText(),afoneTx.getText(),aemailTx.getText(),Long.parseLong(anumeroBrvTx.getText()),Long.parseLong(aregistroTx.getText()),Integer.parseInt(aanoConTx.getText()),anInstTx.getText(),acidadeTx.getText(),aufTx.getText(), expProfissional,tAeronave);
                    
                    //Exceções
                    if(Long.parseLong(anumeroBrvTx.getText())<0){
                        throw new InteiroNegativo(Long.parseLong(anumeroBrvTx.getText()));
                    }
                    if(Long.parseLong(aregistroTx.getText())<0){
                        throw new InteiroNegativo(Long.parseLong(aregistroTx.getText()));
                    }
                    if(Integer.parseInt(aanoConTx.getText())<0){
                        throw new InteiroNegativo(Integer.parseInt(aanoConTx.getText()));
                    }
                    if(Integer.parseInt(acapacidadeTx.getText())<0){
                        throw new InteiroNegativo(Integer.parseInt(acapacidadeTx.getText()));
                    }
                    if(Integer.parseInt(ahTx.getText())<0){
                        throw new InteiroNegativo(Integer.parseInt(ahTx.getText()));
                    }
                    AppMenu.setPosicao(posicaoMudança-1);
                    AppMenu.metodoMenu(piloto,2, mudou); //chamando metodo criado no App Menu para executar a funçao do switch case(1) que no caso é para verificar se existe dados ja cadastrados de um determinado piloto
                    if(AppMenu.Verificado()){
                        
                        JOptionPane.showMessageDialog(this, "Dados Atualizados");                   
                    }
                }catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(this, "Dados invalidos , digite valores numéricos para prosseguir !", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
                catch(InteiroNegativo e){
                        JOptionPane.showMessageDialog(this, e.toString());
                }
            }
    }//GEN-LAST:event_aAtualizarButtonActionPerformed

    private void aConsultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aConsultarButtonActionPerformed
        // TODO add your handling code here:
        boolean procurar = false;
        mudou = false;
        posicaoMudança = 0;
        int tamanho = 0;
        if(anomeTx.getText().equals("") && aregistroTx.getText().equals("") && anumeroBrvTx.getText().equals("") && aemailTx.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Escreva no campo Nome para concluir a pesquisa!", "ERRO", JOptionPane.ERROR_MESSAGE);   
        }
        
        if(!(anomeTx.getText().equals(""))){//Vai procurar so pelo nome , colocou o !(anomeTx) pois entao vai tornar a negaçao da expressao em afirmaçao para concluir a pesquisa
            for(Aviador avi : piloto){
                posicaoMudança++;   // Indica local da mudança no arraylist
                //Vai se fazer uma varredura na busca do nome do piloto consultado
                if(anomeTx.getText().equalsIgnoreCase(avi.getNomeDoAviador())){
                    
                    aviador = avi;
                    expProfissional = avi.getExpProfissional();
                    tAeronave = avi.getTAeronave();
                    
                    anomeTx.setText(avi.getNomeDoAviador());
                    aenderecoTx.setText(avi.getEndereço());
                    afoneTx.setText(avi.getFone());
                    aemailTx.setText(avi.getEmail());
                    anumeroBrvTx.setText(Long.toString(avi.getNumeroBreve()));
                    aregistroTx.setText(Long.toString(avi.getRegistroProf()));
                    aanoConTx.setText(Integer.toString(avi.getAnoDeConclusao()));
                    anInstTx.setText(avi.getNomeDaInstituiçao());
                    acidadeTx.setText(avi.getCidade());
                    aufTx.setText(avi.getUf());
                    adataInicTx.setText(expProfissional.get(posicao).getDataDeInicio());
                    adataTermTx.setText(expProfissional.get(posicao).getDataDeTermino());
                    adescricaoTx.setText(expProfissional.get(posicao).getDescricaoDaAtividade());
                    aempresaTx.setText(expProfissional.get(posicao).getEmpresa());
                    acidadeProfTx.setText(expProfissional.get(posicao).getCidadeProf());
                    aestadoTx.setText(expProfissional.get(posicao).getEstado());
                    amodeloTx.setText(tAeronave.get(posicao).getModelo());
                    acapacidadeTx.setText(Integer.toString(tAeronave.get(posicao).getCapacidade()));
                    ahTx.setText(Integer.toString(tAeronave.get(posicao).getHorasDevoo()));
                    procurar = true;
                }
            }    
            if(!procurar){
                JOptionPane.showMessageDialog(this, "Piloto não Cadastrado!");
            }       
        }
    }//GEN-LAST:event_aConsultarButtonActionPerformed

    private void aLimparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLimparButtonActionPerformed
        // TODO add your handling code here:
        anomeTx.setText("");
        aenderecoTx.setText("");
        afoneTx.setText("");
        aemailTx.setText("");
        anumeroBrvTx.setText("");
        aregistroTx.setText("");
        aanoConTx.setText("");
        anInstTx.setText("");
        acidadeTx.setText("");
        aufTx.setText("");
        adataInicTx.setText("");
        adataTermTx.setText("");
        adescricaoTx.setText("");
        aempresaTx.setText("");
        acidadeProfTx.setText("");
        aestadoTx.setText("");
        amodeloTx.setText("");
        acapacidadeTx.setText("");
        ahTx.setText("");
    }//GEN-LAST:event_aLimparButtonActionPerformed

    private void AnteriorButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorButton2ActionPerformed
        posicao--;
        if(posicao < 0)
            posicao = 0;
        
        expProfissional = aviador.getExpProfissional();
        
        adataInicTx.setText(expProfissional.get(posicao).getDataDeInicio());
        adataTermTx.setText(expProfissional.get(posicao).getDataDeTermino());
        adescricaoTx.setText(expProfissional.get(posicao).getDescricaoDaAtividade());
        aempresaTx.setText(expProfissional.get(posicao).getEmpresa());
        acidadeProfTx.setText(expProfissional.get(posicao).getCidadeProf());
        aestadoTx.setText(expProfissional.get(posicao).getEstado());
        
        expP = expProfissional.get(posicao);
        
    }//GEN-LAST:event_AnteriorButton2ActionPerformed

    private void AlterarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarButton2ActionPerformed
       
        mudou = true;
        
        expP = expProfissional.get(posicao);
        
        if(adataInicTx.getText().toString().equals("  /  /    ") ||adataTermTx.getText().toString().equals("  /  /    ")  || adescricaoTx.getText().toString().equals("") ||  aempresaTx.getText().toString().equals("") || acidadeProfTx.getText().toString().equals("") || aestadoTx.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para prosseguir!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else{
        expP.setDataDeInicio(adataInicTx.getText());
        expP.setDataDeTermino(adataTermTx.getText());
        expP.setDescricaoDaAtividade(adescricaoTx.getText());
        expP.setEmpresa(aempresaTx.getText());
        expP.setEstado(aestadoTx.getText());
        expP.setCidadeProf(acidadeProfTx.getText());
        expProfissional.set(posicao, expP);
        JOptionPane.showMessageDialog(this, "Dados Atualizados");
        
        }
    }//GEN-LAST:event_AlterarButton2ActionPerformed

    private void ProximoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoButton2ActionPerformed
        posicao++;
        
        if(posicao >=  expProfissional.size())
            posicao = expProfissional.size() - 1;
        
        expProfissional = aviador.getExpProfissional();
        
         adataInicTx.setText(expProfissional.get(posicao).getDataDeInicio());

        adataTermTx.setText(expProfissional.get(posicao).getDataDeTermino());
        adescricaoTx.setText(expProfissional.get(posicao).getDescricaoDaAtividade());
        aempresaTx.setText(expProfissional.get(posicao).getEmpresa());
        acidadeProfTx.setText(expProfissional.get(posicao).getCidadeProf());
        aestadoTx.setText(expProfissional.get(posicao).getEstado());
        
        expP = expProfissional.get(posicao);
    }//GEN-LAST:event_ProximoButton2ActionPerformed

    private void ProximoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoButton3ActionPerformed
        // TODO add your handling code here:
        posicao2++;
        
        if(posicao2 >=  tAeronave.size())
            posicao2 = tAeronave.size() - 1;
        
        tAeronave = aviador.getTAeronave();
        amodeloTx.setText(tAeronave.get(posicao2).getModelo());
        acapacidadeTx.setText(Integer.toString(tAeronave.get(posicao2).getCapacidade()));
        ahTx.setText(Integer.toString(tAeronave.get(posicao2).getHorasDevoo()));   
        
        tdaA = tAeronave.get(posicao2);
    }//GEN-LAST:event_ProximoButton3ActionPerformed

    private void AnteriorButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorButton3ActionPerformed
        // TODO add your handling code here:
          
        posicao2--;
        
        if(posicao2 < 0)
            posicao2 = 0;
        
        tAeronave = aviador.getTAeronave();
        
        amodeloTx.setText(tAeronave.get(posicao2).getModelo());
        acapacidadeTx.setText(Integer.toString(tAeronave.get(posicao2).getCapacidade()));
        ahTx.setText(Integer.toString(tAeronave.get(posicao2).getHorasDevoo()));
        
        tdaA = tAeronave.get(posicao2);
    }//GEN-LAST:event_AnteriorButton3ActionPerformed

    private void AlterarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarButton3ActionPerformed
        // TODO add your handling code here:
        mudou = true;
        
        tdaA = tAeronave.get(posicao2);
        
        if(amodeloTx.getText().toString().equals("") ||acapacidadeTx.getText().toString().equals("") || ahTx.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para prosseguir!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else{
        tdaA.setModelo(amodeloTx.getText());
        tdaA.setCapacidade(Integer.parseInt(acapacidadeTx.getText()));
        tdaA.setHorasDevoo(Integer.parseInt(ahTx.getText()));
        tAeronave.set(posicao, tdaA);
        JOptionPane.showMessageDialog(this, "Dados Atualizados");

        }
    }//GEN-LAST:event_AlterarButton3ActionPerformed

    private void aemailTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aemailTxActionPerformed

        if(aviador.getEmail().equalsIgnoreCase(aemailTx.getText()))
            mudou = true;
        
    }//GEN-LAST:event_aemailTxActionPerformed

    private void anomeTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anomeTxKeyTyped
        mudou = true;
    }//GEN-LAST:event_anomeTxKeyTyped

    private void aenderecoTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aenderecoTxKeyTyped
        mudou = true;
    }//GEN-LAST:event_aenderecoTxKeyTyped

    private void afoneTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_afoneTxKeyTyped
        mudou = true;
    }//GEN-LAST:event_afoneTxKeyTyped

    private void aemailTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aemailTxKeyTyped

        mudou = true;
    }//GEN-LAST:event_aemailTxKeyTyped

    private void anumeroBrvTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anumeroBrvTxKeyTyped
        mudou = true;
    }//GEN-LAST:event_anumeroBrvTxKeyTyped

    private void aregistroTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aregistroTxKeyTyped
        mudou = true;
    }//GEN-LAST:event_aregistroTxKeyTyped

    private void aanoConTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aanoConTxKeyTyped
        mudou = true;
    }//GEN-LAST:event_aanoConTxKeyTyped

    private void anInstTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anInstTxKeyTyped
        mudou = true;
    }//GEN-LAST:event_anInstTxKeyTyped

    private void acidadeTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acidadeTxActionPerformed
        mudou = true;
    }//GEN-LAST:event_acidadeTxActionPerformed

    private void aufTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aufTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aufTxActionPerformed

    private void aufTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aufTxKeyTyped
        mudou = true;
    }//GEN-LAST:event_aufTxKeyTyped
    
   //Declaraçoes das variaveis necessarias
    private static LinkedList<Aviador> piloto =  new LinkedList<Aviador>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarButton2;
    private javax.swing.JButton AlterarButton3;
    private javax.swing.JButton AnteriorButton2;
    private javax.swing.JButton AnteriorButton3;
    private javax.swing.JButton ProximoButton2;
    private javax.swing.JButton ProximoButton3;
    private javax.swing.JButton aAtualizarButton;
    private javax.swing.JButton aConsultarButton;
    private javax.swing.JButton aLimparButton;
    private javax.swing.JLabel aanoConLbl;
    private javax.swing.JFormattedTextField aanoConTx;
    private javax.swing.JLabel acapacidadeLbl;
    private javax.swing.JFormattedTextField acapacidadeTx;
    private javax.swing.JLabel acidadeLbl;
    private javax.swing.JLabel acidadeProfLbl;
    private javax.swing.JTextField acidadeProfTx;
    private javax.swing.JTextField acidadeTx;
    private javax.swing.JLabel adadosPessoais;
    private javax.swing.JLabel adataInicLbl;
    private javax.swing.JFormattedTextField adataInicTx;
    private javax.swing.JLabel adataTermLbl;
    private javax.swing.JFormattedTextField adataTermTx;
    private javax.swing.JLabel adescricaoLbl;
    private javax.swing.JTextField adescricaoTx;
    private javax.swing.JLabel aemailLbl;
    private javax.swing.JTextField aemailTx;
    private javax.swing.JLabel aempresaLbl;
    private javax.swing.JTextField aempresaTx;
    private javax.swing.JLabel aenderecoLbl;
    private javax.swing.JTextField aenderecoTx;
    private javax.swing.JLabel aestadoLbl;
    private javax.swing.JTextField aestadoTx;
    private javax.swing.JLabel afoneLbl;
    private javax.swing.JFormattedTextField afoneTx;
    private javax.swing.JLabel ahLbl;
    private javax.swing.JFormattedTextField ahTx;
    private javax.swing.JLabel amodeloLbl;
    private javax.swing.JTextField amodeloTx;
    private javax.swing.JLabel anInstLbl;
    private javax.swing.JTextField anInstTx;
    private javax.swing.JLabel anomeLbl;
    private javax.swing.JTextField anomeTx;
    private javax.swing.JLabel anumeroBrvLbl;
    private javax.swing.JTextField anumeroBrvTx;
    private javax.swing.JLabel aregistroLbl;
    private javax.swing.JTextField aregistroTx;
    private javax.swing.JLabel aufLbl;
    private javax.swing.JTextField aufTx;
    private javax.swing.JLabel ctipoDeAeronave;
    private javax.swing.JLabel ctitulacao;
    private javax.swing.JLabel experienciaProfissional;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
    
    private ArrayList<ExperienciaProfissional> expProfissional;
    private ArrayList<TipoDeAeronave> tAeronave;
    private int posicao = 0, posicao2 = 0;
    private Aviador aviador;
    private ExperienciaProfissional expP;
    private TipoDeAeronave tdaA;
    private boolean mudou = false;
    private int posicaoMudança = 0;
}
