import java.awt.event.KeyEvent;
import javax.swing.*;
import java.lang.*;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.text.MaskFormatter;

public class AppCadastro extends javax.swing.JInternalFrame {
 
    public AppCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadosPessoais = new javax.swing.JLabel();
        nomeLbl = new javax.swing.JLabel();
        nomeTx = new javax.swing.JTextField();
        enderecoLbl = new javax.swing.JLabel();
        enderecoTx = new javax.swing.JTextField();
        foneLbl = new javax.swing.JLabel();
        foneTx = new javax.swing.JFormattedTextField();
        emailLbl = new javax.swing.JLabel();
        emailTx = new javax.swing.JTextField();
        numeroBrvLbl = new javax.swing.JLabel();
        numeroBrvTx = new javax.swing.JTextField();
        registroLbl = new javax.swing.JLabel();
        registroTx = new javax.swing.JTextField();
        titulacao = new javax.swing.JLabel();
        anoConLbl = new javax.swing.JLabel();
        anoConTx = new javax.swing.JFormattedTextField();
        nInstLbl = new javax.swing.JLabel();
        nInstTx = new javax.swing.JTextField();
        cidadeLbl = new javax.swing.JLabel();
        cidadeTx = new javax.swing.JTextField();
        ufLbl = new javax.swing.JLabel();
        ufTx = new javax.swing.JTextField();
        experienciaProfissional = new javax.swing.JLabel();
        dataInicLbl = new javax.swing.JLabel();
        dataInicTx = new javax.swing.JFormattedTextField();
        dataTermLbl = new javax.swing.JLabel();
        dataTermTx = new javax.swing.JFormattedTextField();
        descricaoLbl = new javax.swing.JLabel();
        descricaoTx = new javax.swing.JTextField();
        empresaLbl = new javax.swing.JLabel();
        empresaTx = new javax.swing.JTextField();
        cidadeProfLbl = new javax.swing.JLabel();
        cidadeProfTx = new javax.swing.JTextField();
        estadoLbl = new javax.swing.JLabel();
        estadoTx = new javax.swing.JTextField();
        tipoDeAeronave = new javax.swing.JLabel();
        modeloLbl = new javax.swing.JLabel();
        modeloTx = new javax.swing.JTextField();
        capacidadeLbl = new javax.swing.JLabel();
        capacidadeTx = new javax.swing.JFormattedTextField();
        hLbl = new javax.swing.JLabel();
        hTx = new javax.swing.JFormattedTextField();
        buttonCadastro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        AdicionarButton1 = new javax.swing.JButton();
        Adicionar2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Aviador");

        dadosPessoais.setText(" DADOS PESSOAIS");

        nomeLbl.setText("Nome : ");

        nomeTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxActionPerformed(evt);
            }
        });

        enderecoLbl.setText(" Endereço : ");

        foneLbl.setText(" Fone : ");

        try {
            foneTx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        foneTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foneTxActionPerformed(evt);
            }
        });

        emailLbl.setText(" Email : ");

        numeroBrvLbl.setText(" Número do Brevê (Apenas numeros) : ");

        registroLbl.setText("Registro Profissional(Apenas numeros) : ");

        titulacao.setText(" TITULAÇÃO");

        anoConLbl.setText("(Ano de Conclusão) : ");

        anoConTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoConTxActionPerformed(evt);
            }
        });

        nInstLbl.setText("Nome da Instituição : ");

        cidadeLbl.setText("Cidade : ");

        ufLbl.setText("UF : ");

        experienciaProfissional.setText(" EXPERIÊNCIA PROFISSIONAL");

        dataInicLbl.setText(" Data de inicio : ");

        try {
            dataInicTx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataInicTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataInicTxActionPerformed(evt);
            }
        });

        dataTermLbl.setText("Data de Termino : ");

        try {
            dataTermTx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataTermTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTermTxActionPerformed(evt);
            }
        });

        descricaoLbl.setText(" Descrição da Atividade : ");

        empresaLbl.setText("Empresa : ");

        cidadeProfLbl.setText("Cidade : ");

        estadoLbl.setText("Estado : ");

        tipoDeAeronave.setText("TIPO DE AERONAVE APTA A PILOTAR ");

        modeloLbl.setText(" Modelo : ");

        capacidadeLbl.setText("Capacidade de Passageiros : ");

        hLbl.setText("Horas de Vôo : ");

        buttonCadastro.setText("Cadastrar");
        buttonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroActionPerformed(evt);
            }
        });
        buttonCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonCadastroKeyPressed(evt);
            }
        });

        jButton1.setText("Limpar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AdicionarButton1.setText("Adicionar");
        AdicionarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarButton1ActionPerformed(evt);
            }
        });

        Adicionar2.setText("Adicionar");
        Adicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adicionar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator9)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(anoConLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(anoConTx, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dataInicLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(dataInicTx, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nInstLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(nInstTx, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cidadeLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(cidadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ufLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ufTx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dataTermLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(dataTermTx, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(descricaoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(descricaoTx, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(empresaLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(empresaTx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cidadeProfLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(cidadeProfTx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(estadoLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(estadoTx, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(experienciaProfissional)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AdicionarButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipoDeAeronave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Adicionar2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nomeLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enderecoLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(enderecoTx, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(foneLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(foneTx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(titulacao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(342, 342, 342)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(133, 133, 133)
                                        .addComponent(buttonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(modeloLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(modeloTx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(capacidadeLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(capacidadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(hLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(hTx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(emailLbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(emailTx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(107, 107, 107))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(numeroBrvLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(numeroBrvTx, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)))
                                        .addComponent(registroLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(registroTx, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dadosPessoais)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator10)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(dadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foneTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroBrvLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroBrvTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registroTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anoConLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoConTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nInstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nInstTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(experienciaProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataInicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataInicTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataTermLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataTermTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricaoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricaoTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empresaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empresaTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidadeProfLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidadeProfTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AdicionarButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipoDeAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeloTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidadeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Adicionar2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroActionPerformed
        //Campos formatados vazios abaixo de foneTx , dataInicTx , dataTermTx            
        if(nomeTx.getText().toString().equals("") || enderecoTx.getText().toString().equals("") || foneTx.getText().toString().equals("(  )         ")  || emailTx.getText().toString().equals("") || numeroBrvTx.getText().toString().equals("") || registroTx.getText().toString().equals("") || anoConTx.getText().toString().equals("") || nInstTx.getText().toString().equals("") || cidadeTx.getText().toString().equals("") || ufTx.getText().toString().equals("") || dataInicTx.getText().toString().equals("  /  /    ")  || dataTermTx.getText().toString().equals("  /  /    ")  || descricaoTx.getText().toString().equals("") || empresaTx.getText().toString().equals("")|| cidadeProfTx.getText().toString().equals("") || estadoTx.getText().toString().equals("") || modeloTx.getText().toString().equals("") || capacidadeTx.getText().toString().equals("") || hTx.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para prosseguir!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }else{
                try{
                    //////////////////////////////////////
                    
                    if(!adicionando){
                        expP.setCidadeProf(cidadeProfTx.getText());
                        expP.setDataDeInicio(dataInicTx.getText());
                        expP.setDataDeTermino(dataTermTx.getText());
                        expP.setEmpresa(empresaTx.getText());
                        expP.setEstado(estadoTx.getText());
                        expP.setDescricaoDaAtividade(descricaoTx.getText());
                        
                        expProfissional.add(expP);
                    }
                    
                    if(!adicionando2){
                        tda.setModelo(modeloTx.getText());
                        tda.setCapacidade(Integer.parseInt(capacidadeTx.getText()));
                        tda.setHorasDevoo(Integer.parseInt(hTx.getText()));
                        
                        tAeronave.add(tda);
        
                    }
                    
                    
                    piloto = new Aviador(nomeTx.getText(),enderecoTx.getText(),foneTx.getText(),emailTx.getText(),Long.parseLong(numeroBrvTx.getText()),Long.parseLong(registroTx.getText()),Integer.parseInt(anoConTx.getText()),nInstTx.getText(),cidadeTx.getText(),ufTx.getText(), expProfissional,tAeronave);
                    
                    //Exceções
                    if(Long.parseLong(numeroBrvTx.getText())<0){
                        throw new InteiroNegativo(Long.parseLong(numeroBrvTx.getText()));
                    }
                    if(Long.parseLong(registroTx.getText())<0){
                        throw new InteiroNegativo(Long.parseLong(registroTx.getText()));
                    }
                    if(Integer.parseInt(anoConTx.getText())<0){
                        throw new InteiroNegativo(Integer.parseInt(anoConTx.getText()));
                    }
                    if(Integer.parseInt(capacidadeTx.getText())<0){
                        throw new InteiroNegativo(Integer.parseInt(capacidadeTx.getText()));
                    }
                    if(Integer.parseInt(hTx.getText())<0){
                        throw new InteiroNegativo(Integer.parseInt(hTx.getText()));
                    }
                    AppMenu.metodoMenu(piloto,1, true); //chamando metodo criado no App Menu para executar a funçao do switch case(1) que no caso é para verificar se existe dados ja cadastrados de um determinado piloto
                    if(AppMenu.Verificado()){
                        
                        JOptionPane.showMessageDialog(this, "Dados Cadastrados");                   
                    }
                }catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(this, "Dados invalidos , digite valores numéricos para prosseguir !", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
                catch(InteiroNegativo e){
                        JOptionPane.showMessageDialog(this, e.toString());
                }
            }
    }//GEN-LAST:event_buttonCadastroActionPerformed

    private void nomeTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxActionPerformed

    private void buttonCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonCadastroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastroKeyPressed

    private void foneTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foneTxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_foneTxActionPerformed

    private void dataInicTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataInicTxActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_dataInicTxActionPerformed

    private void anoConTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoConTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoConTxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nomeTx.setText("");
        enderecoTx.setText("");
        foneTx.setText("");
        emailTx.setText("");
        numeroBrvTx.setText("");
        registroTx.setText("");
        anoConTx.setText("");
        nInstTx.setText("");
        cidadeTx.setText("");
        ufTx.setText("");
        dataInicTx.setText("");
        dataTermTx.setText("");
        descricaoTx.setText("");
        empresaTx.setText("");
        cidadeProfTx.setText("");
        estadoTx.setText("");
        modeloTx.setText("");
        capacidadeTx.setText("");
        hTx.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dataTermTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTermTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTermTxActionPerformed

    private void AdicionarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarButton1ActionPerformed
        adicionando = false;
        // Pegando informações dos campos
        if(cidadeTx.getText().toString().equals("") || ufTx.getText().toString().equals("") || dataInicTx.getText().toString().equals("  /  /    ")  || dataTermTx.getText().toString().equals("  /  /    ")  || descricaoTx.getText().toString().equals("") || empresaTx.getText().toString().equals("")|| cidadeProfTx.getText().toString().equals("") || estadoTx.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para prosseguir!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
        expP.setCidadeProf(cidadeProfTx.getText());
        expP.setDataDeInicio(dataInicTx.getText());
        expP.setDataDeTermino(dataTermTx.getText());
        expP.setEmpresa(empresaTx.getText());
        expP.setEstado(estadoTx.getText());
        expP.setDescricaoDaAtividade(descricaoTx.getText());
        
        
        // Adicionando ao ArrayList
        expProfissional.add(expP);
        JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
        //Zerando a variável para adicionar outros
        expP = new ExperienciaProfissional();
        }
    }//GEN-LAST:event_AdicionarButton1ActionPerformed

    private void Adicionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adicionar2ActionPerformed
        // TODO add your handling code here:
        adicionando2 = false;
        // Pegando informações dos campos
        if(modeloTx.getText().toString().equals("") || capacidadeTx.getText().toString().equals("") || hTx.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para prosseguir!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                    tda.setModelo(modeloTx.getText());
                    tda.setCapacidade(Integer.parseInt(capacidadeTx.getText()));
                    tda.setHorasDevoo(Integer.parseInt(hTx.getText()));
        
                    //Exceções
                    if(Integer.parseInt(capacidadeTx.getText())<0){
                        throw new InteiroNegativo(Integer.parseInt(capacidadeTx.getText()));
                    }
                    if(Integer.parseInt(hTx.getText())<0){
                        throw new InteiroNegativo(Integer.parseInt(hTx.getText()));
                    }
                    // Adicionando ao ArrayList
                    else{
                    tAeronave.add(tda);
                    JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
                    //Zerando a variável para adicionar outros
                    tda = new TipoDeAeronave();
                    }
                }catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(this, "Dados invalidos , digite valores numéricos para prosseguir !", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
                catch(InteiroNegativo e){
                        JOptionPane.showMessageDialog(this, e.toString());
                }
        }
    }//GEN-LAST:event_Adicionar2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar2;
    private javax.swing.JButton AdicionarButton1;
    private javax.swing.JLabel anoConLbl;
    private javax.swing.JFormattedTextField anoConTx;
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JLabel capacidadeLbl;
    private javax.swing.JFormattedTextField capacidadeTx;
    private javax.swing.JLabel cidadeLbl;
    private javax.swing.JLabel cidadeProfLbl;
    private javax.swing.JTextField cidadeProfTx;
    private javax.swing.JTextField cidadeTx;
    private javax.swing.JLabel dadosPessoais;
    private javax.swing.JLabel dataInicLbl;
    private javax.swing.JFormattedTextField dataInicTx;
    private javax.swing.JLabel dataTermLbl;
    private javax.swing.JFormattedTextField dataTermTx;
    private javax.swing.JLabel descricaoLbl;
    private javax.swing.JTextField descricaoTx;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTx;
    private javax.swing.JLabel empresaLbl;
    private javax.swing.JTextField empresaTx;
    private javax.swing.JLabel enderecoLbl;
    private javax.swing.JTextField enderecoTx;
    private javax.swing.JLabel estadoLbl;
    private javax.swing.JTextField estadoTx;
    private javax.swing.JLabel experienciaProfissional;
    private javax.swing.JLabel foneLbl;
    private javax.swing.JFormattedTextField foneTx;
    private javax.swing.JLabel hLbl;
    private javax.swing.JFormattedTextField hTx;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel modeloLbl;
    private javax.swing.JTextField modeloTx;
    private javax.swing.JLabel nInstLbl;
    private javax.swing.JTextField nInstTx;
    private javax.swing.JLabel nomeLbl;
    private javax.swing.JTextField nomeTx;
    private javax.swing.JLabel numeroBrvLbl;
    private javax.swing.JTextField numeroBrvTx;
    private javax.swing.JLabel registroLbl;
    private javax.swing.JTextField registroTx;
    private javax.swing.JLabel tipoDeAeronave;
    private javax.swing.JLabel titulacao;
    private javax.swing.JLabel ufLbl;
    private javax.swing.JTextField ufTx;
    // End of variables declaration//GEN-END:variables
   
    //Declaraçao das variaveis necessarias   
    private Aviador piloto; 
    private ArrayList<ExperienciaProfissional> expProfissional = new ArrayList<>();
    private ExperienciaProfissional expP = new ExperienciaProfissional();
    private ArrayList<TipoDeAeronave> tAeronave = new ArrayList<>();
    private TipoDeAeronave tda = new TipoDeAeronave();
    private int posicaoMudanca = 0;
    private boolean adicionando = true, adicionando2 = true;

}
