import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;

public class AppListar extends javax.swing.JInternalFrame {

    public AppListar(LinkedList<Aviador> a) {
        piloto = a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListarButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInheritsPopupMenu(true);

        ListarButton.setText("Listar Pilotos");
        ListarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(ListarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ListarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarButtonActionPerformed
        // TODO add your handling code here:
        Aviador a;
        for(Aviador avi : piloto ){ //é a mesma coisa for(int i=0;i<linkedlist.size();i++)
            JOptionPane.showMessageDialog(null,"Nome: "+avi.getNomeDoAviador()+"\nRegistro Profissional: "+avi.getRegistroProf()+"\nNumero de Brevê: "+avi.getNumeroBreve()); 
        }
    }//GEN-LAST:event_ListarButtonActionPerformed

    
    
    
   //LinkedList e ArrayList's caso precise
    private static LinkedList<Aviador> piloto = new LinkedList<Aviador>();
    private ArrayList<ExperienciaProfissional> expProfissional;
    private ArrayList<TipoDeAeronave> tAeronave;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListarButton;
    // End of variables declaration//GEN-END:variables
}
